### Get action description
GET {{origin}}/virtual-service/actions/grpc-abort


### Prepare abort
POST {{origin}}/virtual-service/actions/grpc-abort/prepare
Content-Type: application/json

{
  "target": {
    "attributes": {
      "istio.virtual-service.name": [
        "bookinfo"
      ],
      "k8s.cluster-name": [
        "minikube"
      ],
      "k8s.namespace": [
        "default"
      ]
    },
    "name": "bookinfo"
  },
  "config": {
    "percentage": 50,
    "statusCode": "CANCELLED"
  }
}

### Start abort
POST {{origin}}/virtual-service/actions/grpc-abort/start
Content-Type: application/json

{
  "state": {
    "Fault": {
      "abort": {
        "grpcStatus": "CANCELLED",
        "percentage": {
          "value": 50
        }
      }
    },
    "Name": "bookinfo",
    "Namespace": "default"
  }
}

### Stop abort
POST {{origin}}/virtual-service/actions/grpc-abort/stop
Content-Type: application/json

{
  "state": {
    "Fault": {
      "abort": {
        "grpcStatus": "CANCELLED",
        "percentage": {
          "value": 50
        }
      }
    },
    "Name": "bookinfo",
    "Namespace": "default"
  }
}
