### Get action description
GET {{origin}}/virtual-service/actions/grpc-abort


### Prepare abort
POST {{origin}}/virtual-service/actions/grpc-abort/prepare
Content-Type: application/json

{
  "executionId": "22955847-b455-461d-8f9b-61ef1ef05060",
  "target": {
    "attributes": {
      "istio.virtual-service.name": [
        "bookinfo"
      ],
      "k8s.cluster-name": [
        "minikube"
      ],
      "k8s.namespace": [
        "default"
      ]
    },
    "name": "bookinfo"
  },
  "config": {
    "percentage": 50,
    "statusCode": "CANCELLED",
    "headers": [
      {
        "key": "x-request-id",
        "value": "22955847-b455-461d-8f9b-61ef1ef05060"
      }
    ],
    "headersMatchType": "prefix",
    "sourceLabels": [
      {
        "key": "app",
        "value": "shop"
      }
    ]
  }
}

### Start abort
POST {{origin}}/virtual-service/actions/grpc-abort/start
Content-Type: application/json

{
  "state": {
    "Fault": {
      "abort": {
        "grpcStatus": "CANCELLED",
        "percentage": {
          "value": 50
        }
      }
    },
    "FaultyRoutePrefix": "steadybit-injected-fault_22955847-b455-461d-8f9b-61ef1ef05060",
    "Headers": {
      "x-request-id": {
        "prefix": "22955847-b455-461d-8f9b-61ef1ef05060"
      }
    },
    "Name": "bookinfo",
    "Namespace": "default",
    "SourceLabels": {
      "app": "shop"
    }
  }
}

### Stop abort
POST {{origin}}/virtual-service/actions/grpc-abort/stop
Content-Type: application/json

{
  "state": {
    "Fault": {
      "abort": {
        "grpcStatus": "CANCELLED",
        "percentage": {
          "value": 50
        }
      }
    },
    "FaultyRoutePrefix": "steadybit-injected-fault_22955847-b455-461d-8f9b-61ef1ef05060",
    "Headers": {
      "x-request-id": {
        "prefix": "22955847-b455-461d-8f9b-61ef1ef05060"
      }
    },
    "Name": "bookinfo",
    "Namespace": "default",
    "SourceLabels": {
      "app": "shop"
    }
  }
}
