### Get action description
GET {{origin}}/virtual-service/actions/http-abort


### Prepare abort
POST {{origin}}/virtual-service/actions/http-abort/prepare
Content-Type: application/json

{
  "executionId": "22955847-b455-461d-8f9b-61ef1ef05060",
  "target": {
    "attributes": {
      "istio.virtual-service.name": [
        "bookinfo"
      ],
      "k8s.cluster-name": [
        "minikube"
      ],
      "k8s.namespace": [
        "default"
      ]
    },
    "name": "bookinfo"
  },
  "config": {
    "percentage": 50,
    "statusCode": 500
  }
}

### Start abort
POST {{origin}}/virtual-service/actions/http-abort/start
Content-Type: application/json

{
  "state": {
    "Fault": {
      "abort": {
        "httpStatus": 500,
        "percentage": {
          "value": 50
        }
      }
    },
    "FaultyRoutePrefix": "steadybit-injected-fault_22955847-b455-461d-8f9b-61ef1ef05060",
    "Name": "bookinfo",
    "Namespace": "default"
  }
}

### Stop abort
POST {{origin}}/virtual-service/actions/http-abort/stop
Content-Type: application/json

{
  "state": {
    "Fault": {
      "abort": {
        "httpStatus": 500,
        "percentage": {
          "value": 50
        }
      }
    },
    "FaultyRoutePrefix": "steadybit-injected-fault_22955847-b455-461d-8f9b-61ef1ef05060",
    "Name": "bookinfo",
    "Namespace": "default"
  }
}
