### Get action description
GET {{origin}}/virtual-service/actions/http-delay


### Prepare delay
POST {{origin}}/virtual-service/actions/http-delay/prepare
Content-Type: application/json

{
  "executionId": "22955847-b455-461d-8f9b-61ef1ef05060",
  "target": {
    "attributes": {
      "istio.virtual-service.name": [
        "bookinfo"
      ],
      "k8s.cluster-name": [
        "minikube"
      ],
      "k8s.namespace": [
        "default"
      ]
    },
    "name": "bookinfo"
  },
  "config": {
    "percentage": 50,
    "delay": 5000
  }
}

### Start delay
POST {{origin}}/virtual-service/actions/http-delay/start
Content-Type: application/json

{
  "state": {
    "Fault": {
      "delay": {
        "fixedDelay": "5s",
        "percentage": {
          "value": 50
        }
      }
    },
    "FaultyRoutePrefix": "steadybit-injected-fault_22955847-b455-461d-8f9b-61ef1ef05060",
    "Name": "bookinfo",
    "Namespace": "default"
  }
}

### Stop delay
POST {{origin}}/virtual-service/actions/http-delay/stop
Content-Type: application/json

{
  "state": {
    "Fault": {
      "delay": {
        "fixedDelay": "5s",
        "percentage": {
          "value": 50
        }
      }
    },
    "FaultyRoutePrefix": "steadybit-injected-fault_22955847-b455-461d-8f9b-61ef1ef05060",
    "Name": "bookinfo",
    "Namespace": "default"
  }
}
